let obj = {
  "/CodingTool/": [{
    "title": "CodingTool",
    "collapsable": true,
    "sidebarDepth": 4,
    "children": ["./docs/CodingTool/Vue_cli.md",
      "./docs/CodingTool/Git/git&github.md",
      "./docs/CodingTool/Git/git_geektime.md",

      "./docs/CodingTool/Git/how_to_keep_sync_with_fork_project.md",
      "./docs/CodingTool/Webpack/chips.md",
      "./docs/CodingTool/Webpack/webpack_geektime.md"]
  }],
  "/IdeaPills/": [{
    "title": "IdeaPills",
    "collapsable": true,
    "sidebarDepth": 4,
    "children": ["./docs/IdeaPills/idea_term_1.md",
      "./docs/IdeaPills/idea_term_10.md",
      "./docs/IdeaPills/idea_term_11.md",
      "./docs/IdeaPills/idea_term_12.md",
      "./docs/IdeaPills/idea_term_2.md",
      "./docs/IdeaPills/idea_term_4.md",
      "./docs/IdeaPills/idea_term_3.md",
      "./docs/IdeaPills/idea_term_5.md",
      "./docs/IdeaPills/idea_term_6.md",
      "./docs/IdeaPills/idea_term_7.md",
      "./docs/IdeaPills/idea_term_9.md",
      "./docs/IdeaPills/idea_term_8.md"]
  }],
  "/Interview/": [{
    "title": "Interview",
    "collapsable": true,
    "sidebarDepth": 4,
    "children": ["./docs/Interview/interview.md",
      "./docs/Interview/interview_summary.md",
      "./docs/Interview/nowcoder_record.md"]
  }],
  "/LeetCode/": [{
    "title": "LeetCode",
    "collapsable": true,
    "sidebarDepth": 4,
    "children": [
      "./docs/LeetCode/1.two_num_sum.md",
      "./docs/LeetCode/121.chance_to_trade.md",
      "./docs/LeetCode/14.comon_prefix.md",
      "./docs/LeetCode/13.romeToInteger.md",
      "./docs/LeetCode/189.reverse_array.md",
      "./docs/LeetCode/20.valid_brace.md",
      "./docs/LeetCode/26.delete_duplicate_in_array.md",
      "./docs/LeetCode/28.achieve_strstr.md",
      "./docs/LeetCode/27.delete_item.md",
      "./docs/LeetCode/3.lengthOfLongestSubstring.md",
      "./docs/LeetCode/35.find_insert_position.md",
      "./docs/LeetCode/4.findMedianSortedArrays.md",
      "./docs/LeetCode/67.binary_sum.md",
      "./docs/LeetCode/7.integer_reverse.md",
      "./docs/LeetCode/9.palindromic.md"]
  }],
  "/Others/" : [{
    "title": "Others",
    "collapsable": true,
    "sidebarDepth": 4,
    "children": [
      "./docs/Others/anything_about_wechat.md",
      "./docs/Others/bug_analysis.md",
      "./docs/Others/comlete_determine_sytem.md",
      "./docs/Others/command_line_trick.md",
      "./docs/Others/common_ag.md",
      "./docs/Others/cycling_taiwan.md",
      "./docs/Others/frame_lib_sdk.md",
      "./docs/Others/FEwechater.md",
      "./docs/Others/get_my_money_back.md",
      "./docs/Others/get_outdoor_info.md",
      "./docs/Others/life_efficiency.md",
      "./docs/Others/make_blog.md",
      "./docs/Others/MVC、MVP&MVVM.md",
      "./docs/Others/recommend_an_app.md",
      "./docs/Others/repair_of_nuc.md",
      "./docs/Others/the_cognition_gain_in_market.md",
      "./docs/Others/the_thanks_to_zcl.md",
      "./docs/Others/time_tracker.md",
      "./docs/Others/try_to_touch_the_market.md",
      "./docs/Others/wechatread_use.md",
      "./docs/Others/wrong.md"]
  }],
  "/Projects/" : [{
    "title": "Projects",
    "collapsable": true,
    "sidebarDepth": 4,
    "children": [
      "./docs/Projects/make_blog_with_vuepress.md",
      "./docs/Projects/map_of_data_center.md",
      "./docs/Projects/music_bulk_download.md",
      "./docs/Projects/node_todo.md",
      "./docs/Projects/page_screenshot.md",
      "./docs/Projects/puppeteer_get_image.md",
      "./docs/Projects/node_getArticle.md",
      "./docs/Projects/vue_wheels_button.md",
      "./docs/Projects/vue_wheels_grid.md",
      "./docs/Projects/vue_wheels_compos_name.md",
      "./docs/Projects/vue_wheels_input.md",
      "./docs/Projects/vue_wheels_layout.md",
      "./docs/Projects/vue_wheels_popover.md",
      "./docs/Projects/vue_wheels_primary_conclusion.md",
      "./docs/Projects/vue_wheels_start.md",
      "./docs/Projects/vue_wheels_toast.md",
      "./docs/Projects/vue_wheels_tabs.md"]
  }],
  "/Reading/" : [{
    "title": "Reading",
    "collapsable": true,
    "sidebarDepth": 4,
    "children": [
      "./docs/Reading/charles_munger.md",
      "./docs/Reading/Benjamin_Franklin.md",
      "./docs/Reading/dog_money.md",
      "./docs/Reading/civilization_modernization_valueInvestment_china.md",
      "./docs/Reading/how_to_learn_efficiently.md",
      "./docs/Reading/how_to_do_well_in_internet.md",
      "./docs/Reading/index_funds.md",
      "./docs/Reading/invest_for_decades.md",
      "./docs/Reading/replay.md",
      "./docs/Reading/the_rich_father_investment.md",
      "./docs/Reading/value_what_i_thought_during_the_investment.md",
      "./docs/Reading/writing_is_investing.md",
      "./docs/Reading/xiaomin_qin.md",
      "./docs/Reading/xiaoping_cushijian.md"]
  }],
  "/LearnTech/": [{
    "title": "Browser",
    "collapsable": true,
    "sidebarDepth": 4,
    "children": [
      "./docs/LearnTech/Browser/cache.md",
      "./docs/LearnTech/Browser/character_byte_chinese.md",
      "./docs/LearnTech/Browser/devtools.md",
      "./docs/LearnTech/Browser/how_browser_works.md",
      "./docs/LearnTech/Browser/page_performance_optimize.md",
      "./docs/LearnTech/Browser/url_to_display.md",
      "./docs/LearnTech/HTTP/http_cache.md",
      "./docs/LearnTech/HTTP/http_https.md",
      "./docs/LearnTech/HTML/Dom.md",
      "./docs/LearnTech/Flutter/flutter_geektime.md",
      "./docs/LearnTech/CSS/BFC.md",
      "./docs/LearnTech/CSS/block_inline_inlineBlock.md",
      "./docs/LearnTech/CSS/box_module.md",
      "./docs/LearnTech/CSS/css_font.md",
      "./docs/LearnTech/CSS/css_hard_to_learn.md",
      "./docs/LearnTech/CSS/css_img_stretch.md",
      "./docs/LearnTech/CSS/element_to_center.md",
      "./docs/LearnTech/CSS/flex.md",
      "./docs/LearnTech/CSS/mobile_page.md",
      "./docs/LearnTech/CSS/preudo.md",
      "./docs/LearnTech/CSS/Sass.md",
      "./docs/LearnTech/Javascript/advanced_program_design.md",
      "./docs/LearnTech/Javascript/apply_call_bind.md",
      "./docs/LearnTech/Javascript/babel.md",
      "./docs/LearnTech/Javascript/event_bind.md",
      "./docs/LearnTech/Javascript/event_loop_translate.md",
      "./docs/LearnTech/Javascript/filter_in_array.md",
      "./docs/LearnTech/Javascript/forin_forof.md",
      "./docs/LearnTech/Javascript/func_declare_expression.md",
      "./docs/LearnTech/Javascript/hand_writing.md",
      "./docs/LearnTech/Javascript/Iterator_generator.md",
      "./docs/LearnTech/Javascript/js_arrow_func.md",
      "./docs/LearnTech/Javascript/js_async.md",
      "./docs/LearnTech/Javascript/js_dataType.md",
      "./docs/LearnTech/Javascript/js_destructuring_assign.md",
      "./docs/LearnTech/Javascript/js_datatype_convert.md",
      "./docs/LearnTech/Javascript/js_excute_context.md",
      "./docs/LearnTech/Javascript/js_grammar.md",
      "./docs/LearnTech/Javascript/js_inherit.md",
      "./docs/LearnTech/Javascript/js_modules.md",
      "./docs/LearnTech/Javascript/js_oop.md",
      "./docs/LearnTech/Javascript/js_new_api.md",
      "./docs/LearnTech/Javascript/js_new.md",
      "./docs/LearnTech/Javascript/js_proto_chain.md",
      "./docs/LearnTech/Javascript/let_const_interview.md",
      "./docs/LearnTech/Javascript/new_string.md",
      "./docs/LearnTech/Javascript/property_modification.md",
      "./docs/LearnTech/Javascript/reduce_in_array.md",
      "./docs/LearnTech/Javascript/this.md",
      "./docs/LearnTech/Javascript/tool_function.md",
      "./docs/LearnTech/Node/about_node.md",
      "./docs/LearnTech/Node/fs_module.md",
      "./docs/LearnTech/Node/http_url_module.md",
      "./docs/LearnTech/Node/mongoDB.md",
      "./docs/LearnTech/Kaikeba/chapter_2.md",
      "./docs/LearnTech/Kaikeba/chapter_4.md",
      "./docs/LearnTech/Kaikeba/chapter_5.md",
      "./docs/LearnTech/NetCourse/FEer_advance.md",
      "./docs/LearnTech/NetCourse/fe_attack.md",
      "./docs/LearnTech/NetCourse/geektime_git.md",
      "./docs/LearnTech/NetCourse/js_deep.md",
      "./docs/LearnTech/NetCourse/js_core.md",
      "./docs/LearnTech/NetCourse/office_ability.md"]
  }]
}
